server:
  port: 1111
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rokrLearn/CentralRepo
          username: rokrLearn
          password: my@ccPass12
  profiles:
    active: native
      
        
