spring:
#  datasource:
#    url: jdbc:h2:mem:travellerdb
#    driverClassName: org.h2.Driver
#    username: admin
#    password: admin
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true    
  application:
    name: travellerEurekaClient
    
#eureka:          
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    preferIpAddress: true
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}  